#Web
web:
  build: ./docker/builds/php_apache
  ports:
    - "9009:80"
  volumes:
    - "./webapp:/app"
  links:
    - mariadb

mariadb:
  image: mariadb:latest
  ports:
    - "3310:3306"
  environment:
    MYSQL_ROOT_PASSWORD: q1w2e3r4
    MYSQL_DATABASE: boilepate
    MYSQL_USER: db_user
    MYSQL_PASSWORD: db_pass
  volumes:
    - "./storage/db/mariadb:/var/lib/mysql"
    - "./storage/dumps:/dumps"